services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    env_file:
      - path: ../.env
        required: false
    command: sleep infinity
